### ISSUE TITLE
run fetch_selective_search_data.sh fail

### ISSUE THREAD

**Issue by dongxijia** [adityaarun1/pytorch_fast-er_rcnn#1]
`Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|208.43.170.231|:443... failed: Connection refused`

Can you offer a now url for that, thanks very much.

**Comment by adityaarun1** [comment]
Weird, even the home page of [Jasper Uijlings](http://homepages.inf.ed.ac.uk/juijling/index.php) (the original author) is down. You can alternatively download the proposals from [here](https://www.koen.me/research/selectivesearch/). Thanks for pointing this out though.
